import type { Metadata } from "next";
import "../admin/adminGlobals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { DashboardSidebar } from "@/components/admin/dashboard/sidebar";
import { SidebarProvider } from "@/components/admin/sidebar-provider";
import { DashboardHeader } from "@/components/admin/dashboard/header";
import TanstackProviders from "@/components/Providers";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Piyush",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        <SidebarProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TanstackProviders>
              <div className="flex min-h-screen flex-col">
                <DashboardHeader />
                <div className="flex flex-1">
                  <DashboardSidebar />
                  <main className="flex-1 p-4 md:p-6">{children}</main>
                </div>
              </div>
            </TanstackProviders>
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
