import type { Metadata } from "next";
import "./homeGlobals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Footer from "@/components/Footer";
import TanstackProviders from "@/components/Providers";
import RootNavbar from "@/components/RootNavbar";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Piyush",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackProviders>
            <RootNavbar />
            <main className="">
              <div className=" relative">{children}</div>
            </main>
            <Footer />
          </TanstackProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
